[project]
name = "agno-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.5.5",
    "duckduckgo-search>=8.0.2",
    "ollama>=0.4.9",
]
